### PR TITLE
Adding action execution status (as color changes) to the plan dotgraph.

### PR DESCRIPTION
**Pull request by xydesa**
Adding legend to plan dotgraph, adding node params for dotgraph legend and printing plan graph to terminal.

Signed-off-by: Alexander Xydes <alexander.xydes@navy.mil>

*Testing*
* Basing the test off of the bt example in the ros2_planning_system_examples repository.
  * https://github.com/IntelligentRoboticsLabs/ros2_planning_system_examples/tree/master/plansys2_bt_example
* Create a workspace from this repos file: 
[plansys2-dotgraph-action-status.repos.txt](https://github.com/IntelligentRoboticsLabs/ros2_planning_system/files/6314367/plansys2-dotgraph-action-status.repos.txt)
* Terminal 1: `ros2 launch nav2_bringup tb3_simulation_launch.py`
* Terminal 2: `ros2 launch plansys2_bt_example plansys2_bt_example_launch.py`
* Terminal 3: `ros2 run rqt_dotgraph rqt_dotgraph`
* Terminal 4:
```
ros2 run plansys2_terminal plansys2_terminal
set instance r2d2 robot

set instance wheels_zone zone
set instance steering_wheels_zone zone
set instance body_car_zone zone
set instance assembly_zone zone

set instance wheel_1 piece
set instance body_car_1 piece
set instance steering_wheel_1 piece

set predicate (piece_at wheel_1 wheels_zone)
set predicate (piece_at body_car_1 body_car_zone)
set predicate (piece_at steering_wheel_1 steering_wheels_zone)

set predicate (robot_at r2d2 assembly_zone)

set goal (and(piece_at wheel_1 assembly_zone))
run
```
* After you type `run` and hit enter in Terminal 4 and the plan starts executing, you should see the plan in the rqt_dotgraph window. It should look something like this:
dotgraph-action-status

### CODE REVIEW

**Comment by fmrico** [comment]
Hi @xydesa 

Awesome!! I really love this PR and your work with Dot Graph. 

I am testing it, but all the actions are in blue while executing the plan. Do I need anything else?

**Comment by fmrico** [comment]
After merging #111 , it seems to be a small conflict. Please, rebase or merge it ;)

**Comment by xydesa** [comment]
@fmrico I'm not sure why you're seeing all the actions in blue. I'm not seeing this, maybe it was because of the need to merge master in? Let me know if you're still seeing this after testing the latest (since master was merged in).

I'm seeing the following after I merged master in:
step-1
step-2
step-3

**Comment by fmrico** [comment]
Ok!! Merging.

Thanks!!

**Pull request merged**
