### PR TITLE
Improvements on recent BtActionNode changes

### PR DESCRIPTION
**Pull request by sarcasticnature**
The recent changes to BtActionNode made by @fmrico left a few artifacts of the old tick method behind; this PR removes them and adds a few QOL changes along the way

### CODE REVIEW

**Comment by sarcasticnature** [comment]
@fmrico: There is a bug that appeared in some of my (non-ros2_planning_system) code which I believe to have chased back to the `plansys2_bt_actions` package, see #210 for details.  Should we wait for a fix for that bug or merge this as is?

**Comment by sarcasticnature** [comment]
the most recent commit resolves #210

**Comment by fmrico** [comment]
Thanks @sarcasticnature 

merging !!!!! :rocket:

**Comment by sarcasticnature** [comment]
I normally do but I'm a bit... lazy about it when I'm the only one pushing to a repo.  If it helps you out for future PRs I will do so going forward

**Pull request merged**
