### PR TITLE
Increase default server tiemout

### PR DESCRIPTION
**Pull request by fmrico**
Hi,

Last merges, which tests passed (both in local and in CI separately), makes the tests fail in master. This PR is to investigate and to fix this.

Best

Signed-off-by: Francisco Martín Rico <fmrico@gmail.com>

### CODE REVIEW

**Comment by sarcasticnature** [comment]
I believe it's due to the race condition I have been speculating about in my other PR.  I think what is happening is that the ROS action server is sending a goal result without ever sending feedback, which is causing the test to fail

**Comment by sarcasticnature** [comment]
add a delay in the test server to allow time for the feedback to send before it returns success.  I can't work on a fix at this moment, but should be able to knock something out tonight

**Comment by fmrico** [comment]
Tests in PR works, but not in master... :thinking:

**Comment by sarcasticnature** [comment]
The line you changed increased the amount of time the node will wait for an action server to be available, which does not add any delay.  I may have a fix but will need to create a PR to see if it passes CI

**Pull request merged**
