### PR TITLE
Subtyping

### LINKED ISSUE #40: PDDL typing : Only the terminal type is taken into account
When a predicate or a function is affected, a type checking is performed in order to refuse the "mis-typed" operations.

Considering the following types :
```pddl
(:types 
        T1   - object
        T2   - T1
        T3   - T1
    )
```
 and the following predicate :

```pddl
(:predicates 
        (isPredicate ?in - T1)
    )
```
And performing the following instances declarations:
* `set instance o1 T1`
* `set instance o2 T2`

Then, the following instance affectation will be:
* :heavy_check_mark: : `set predicate  (isPredicate o1)`
* :x: : `set predicate  (isPredicate o2)`

According to PDDL types hierarchy, both of the above expressions should be accepted.

How do you thing this issue should be addressed ? Is the types "Instance" struct shall be promoted to a class with a "is" method in order to hkeck a type ? something else ?

### PR DESCRIPTION
**Pull request by teyssieuman**
Fixes #40

### CODE REVIEW

**Comment by fmrico** [comment]
Hi @teyssieuman 

Could you please add tests (like [this](https://github.com/IntelligentRoboticsLabs/ros2_planning_system/tree/master/plansys2_planner/test), for example) to test your contribution?

I will be fixing the CI this week.

Thanks!!

**Comment by teyssieuman** [comment]
What about modifying (increasing) an existing test instead of creating a new one (problem_expert tests for example) ?

Or do you prefer me to create a new one ?

**Comment by teyssieuman** [comment]
Hi @fmrico, I just add some tests, what about those ?

**Comment by fmrico** [comment]
Hi @teyssieuman 

I prefer having both domains for tests. Usually, this is incremental to ensure that we don't break what was previously working.

BTW, I have changed the CI in #45 . Maybe you should rebase if it is merged.

Thanks!!

**Comment by teyssieuman** [comment]
Rebase made ... I will try to improve test now.

**Comment by teyssieuman** [comment]
@fmrico I just added some tests the `domain_expert`.

**Comment by fmrico** [comment]
Excellent!! Thanks for your contribution :)

**Pull request merged**
